const actionType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',

  GET_POSTS: 'GET_POSTS',
  GET_POSTS_PAGINATION: 'GET_POSTS_PAGINATION',
  GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
  GET_NEW_POSTS: 'GET_NEW_POSTS',

  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRICES: 'GET_PRICES',
  GET_AREAS: 'GET_AREAS',
  GET_PROVINCES: 'GET_PROVINCES',

  //USER
  GET_CURRENT_USER: 'GET_CURRENT_USER'
}

export default actionType
