const actionType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',

  GET_POSTS: 'GET_POSTS',
  GET_POSTS_PAGINATION: 'GET_POSTS_PAGINATION'
}

export default actionType
